baseURL = "https://wulouie7-ai.github.io/web-site/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
publishDir = "docs"
[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  mainSections = ["posts"]

